Repository hassio-addons/addon-aircast, pull requests merged in 2022-01, with the labels that each got.

#125 Add logo and icon
  aircast/icon.png
  aircast/icon@2x.png
  aircast/logo.png
  aircast/logo@2x.png
Labels: enhancement

#127 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  aircast/.README.j2
  aircast/DOCS.md
Labels: maintenance

#128 ⬆️ Upgrades add-on base image to 5.2.3
  aircast/Dockerfile
  aircast/build.yaml
Labels: dependencies
